refactor: consolidate workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,18 +1,16 @@
-name: Deploy Lambda Functions
+name: Deploy Lambda
 
 on:
-  workflow_run:
-    workflows: ["Deploy Lambda Layers"]
-    types:
-      - completed
+  push:
+    branches:
+      - "**"
 
 jobs:
   deploy:
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
 
     env:
-      S3_BUCKET: ${{ vars.FUNCTIONS_S3_BUCKET }}
+      LAYERS_S3_BUCKET: ${{ vars.LAYERS_S3_BUCKET }}
       REGION: ${{ vars.REGION }}
 
     steps:
@@ -30,6 +28,88 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.REGION }}
+
+      - name: Get layer directories
+        id: layer_dirs
+        run: |
+          echo "Detecting changed layer directories..."
+          BEFORE=${{ github.event.before }}
+          AFTER=${{ github.event.after }}
+
+          if git cat-file -e "$BEFORE"^{commit} &>/dev/null; then
+            echo "Commit $BEFORE found."
+            DIRS=$(git diff --name-only "$BEFORE" "$AFTER" | awk -F/ '$1 == "layers" && NF>=2 && $1 !~ /^\./ && $2 !~ /^\./ {print $1 "/" $2}' | sort -u)
+          else
+            echo "Commit $BEFORE NOT found. First commit."
+            DIRS=$(find . -mindepth 2 -maxdepth 2 -type d -not -path '*/.*' | cut -c 3- | sort -u | awk -F/ '$1 == "layers"')
+          fi
+
+          if [[ -z "$DIRS" ]]; then
+            echo "No changed layer directories found. Skipping deployment."
+          else
+            echo "Changed layer directories:"
+            echo "$DIRS"
+            echo "dirs<<EOF" >> $GITHUB_OUTPUT
+            echo "$DIRS" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Package and deploy layers
+        if: steps.layer_dirs.outputs.dirs != ''
+        run: |
+          set -euo pipefail
+
+          TIMESTAMP=$(date +%Y%m%d%H%M%S)
+          COMMIT_SHA=${{ github.sha }}
+          BRANCH="${{ github.ref_name }}"
+
+          DEPLOY_ALIAS=$(./scripts/get-alias.sh "$BRANCH")
+          echo "Branch '$BRANCH' will deploy to alias: $DEPLOY_ALIAS"
+
+          while IFS= read -r path; do
+            LAYER=$(basename "$path")
+
+            CONFIG_FILE="${path}/config.json"
+            if [[ ! -f "$CONFIG_FILE" ]]; then
+              echo "Missing config.json in $path, skipping..."
+              continue
+            fi
+
+            LAYER_NAME=$(jq -r .name "$CONFIG_FILE")
+            DESCRIPTION=$(jq -r .description "$CONFIG_FILE")
+            TYPE=$(jq -r .type "$CONFIG_FILE")
+            COMPATIBLE_RUNTIMES=$(jq -c .runtimes "$CONFIG_FILE")
+
+            ZIP_FILE="${LAYER}-${TIMESTAMP}-${COMMIT_SHA}.zip"
+            S3_KEY="${LAYER}/${ZIP_FILE}"
+
+            echo "Zipping $path..."
+            cd "$path"
+            ./scripts/install-packages.sh "$TYPE"
+
+            zip -r "../../$ZIP_FILE" . > /dev/null
+            cd - > /dev/null
+
+            echo "Uploading to s3://${LAYERS_S3_BUCKET}/${S3_KEY}"
+            aws s3 cp "$ZIP_FILE" "s3://${LAYERS_S3_BUCKET}/${S3_KEY}"
+
+            echo "Publishing new layer version..."
+            ACCOUNT_NUMBER=$(aws sts get-caller-identity --query Account --output text)
+            VERSION=$(aws lambda publish-layer-version \
+          --layer-name "arn:aws:lambda:$REGION:$ACCOUNT_NUMBER:layer:$LAYER_NAME" \
+              --description "$DESCRIPTION" \
+              --content S3Bucket="$LAYERS_S3_BUCKET",S3Key="$S3_KEY" \
+              --compatible-runtimes "$COMPATIBLE_RUNTIMES" \
+              --region "$REGION" \
+              --output text \
+              --query 'Version')
+
+            echo "Published version $VERSION of $LAYER_NAME"
+
+            echo "Cleaning up..."
+            rm "$ZIP_FILE"
+
+          done <<< "${{ steps.layer_dirs.outputs.dirs }}"
 
       - name: Get Lambda directories
         id: function_dirs
@@ -94,15 +174,15 @@ jobs:
             zip -r "../../../$ZIP_FILE" . > /dev/null
             cd - > /dev/null
 
-            echo "Uploading to s3://${S3_BUCKET}/${S3_KEY}"
-            aws s3 cp "$ZIP_FILE" "s3://${S3_BUCKET}/${S3_KEY}"
+            echo "Uploading to s3://${FUNCTIONS_S3_BUCKET}/${S3_KEY}"
+            aws s3 cp "$ZIP_FILE" "s3://${FUNCTIONS_S3_BUCKET}/${S3_KEY}"
 
             echo "Checking if Lambda function ${FUNCTION_NAME} exists..."
             if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" >/dev/null 2>&1; then
               echo "Updating Lambda ${FUNCTION_NAME}..."
               aws lambda update-function-code \
                 --function-name "$FUNCTION_NAME" \
-                --s3-bucket "$S3_BUCKET" \
+                --s3-bucket "$FUNCTIONS_S3_BUCKET" \
                 --s3-key "$S3_KEY" \
                 --region "$REGION"
             else
@@ -112,7 +192,7 @@ jobs:
                 --runtime "$RUNTIME" \
                 --role "$IAM_ROLE_ARN" \
                 --handler "$HANDLER" \
-                --code S3Bucket="$S3_BUCKET",S3Key="$S3_KEY" \
+                --code S3Bucket="$FUNCTIONS_S3_BUCKET",S3Key="$S3_KEY" \
                 --region "$REGION"
             fi
 
@@ -121,15 +201,17 @@ jobs:
               --function-name "$FUNCTION_NAME" \
               --region "$REGION"
 
-            echo "Updating layers for ${FUNCTION_NAME}..."
-            aws lambda update-function-configuration \
-            --function-name "$FUNCTION_NAME" \
-            --layers $LAYERS
-
-            # Wait for function update to finish
-            aws lambda wait function-updated \
+            if [[ -n $LAYERS ]]; then
+              echo "Updating layers for ${FUNCTION_NAME}..."
+              aws lambda update-function-configuration \
               --function-name "$FUNCTION_NAME" \
-              --region "$REGION"
+              --layers $LAYERS
+
+              # Wait for function update to finish
+              aws lambda wait function-updated \
+                --function-name "$FUNCTION_NAME" \
+                --region "$REGION"
+            fi
 
             echo "Publishing new version for ${FUNCTION_NAME}..."
             VERSION=$(aws lambda publish-version \
